version: "3"
volumes: 
  postgres_data:

services:
    postgres:
      container_name: todo-app-postgres
      image: postgres:14.6-alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: todos
      ports:
        - '5432:5432'
      volumes: 
        - postgres_data:/var/lib/postgresql/data
    backend:
      container_name: todo-app-back
      image: ekajto/todo-app-back-inz-sys-proj-zal
      build:
        context: ./backend/
        dockerfile: Dockerfile
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: todos
      ports:
        - "8000:8000"
      depends_on:
        - postgres
    frontend:
      container_name: todo-app-front
      image: ekajto/todo-app-front-inz-sys-proj-zal
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      environment:
        BACKEND_APP_PORT: 8000
      ports:
        - "80:80"
      depends_on:
        - backend


