apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-front-deployment
  labels:
    app: todo-app-front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app-front-pod
  template:
    metadata:
      labels:
        app: todo-app-front-pod
    spec:
      containers:
      - name: todo-app-front-container
        image: ekajto/todo-app-front-inz-sys-proj-zal
        ports:
        - containerPort: 80
