apiVersion: v1
kind: Service
metadata:
  name: todo-app-front-service
  labels:
    app: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: todo-app-front-pod
  ports:
  - port: 80
    targetPort: 80