apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-pv-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      containers:
        - name: postgres
          image: postgres:14.6-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: cm
            - secretRef:
                name: secrets
          volumeMounts:
            -  name: postgres-pv-storage
               mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory:
